### ISSUE TITLE
1.14.1 release?

### ISSUE THREAD

**Issue by ashawley** [typelevel/scalacheck#453]
The last release of ScalaCheck was on Apr-22 2018.

Here's a proposal for a release:

## 1.14.1

Here are things already merged to master since 1.14.0:

* [x] Fix `Arbitrary[Option[T]]` so it is equivalent to `Gen[Option[T]]` #401
* [x] Allow `Gen.oneOf` to take argument of `Iterable` #438
* [x] Fix compilation error in Cogen with Scala 2.11.12 #403
* [x] Update Scala.js 1.x to 1.0.0-M6 #460 
* [x] Fix compilation error in test runner for Java 9 and later #406
* [x] Fix compilation error in pretty-printer for Java 11 and later #430
* [x] Fix deprecation in ScalaCheck's internal tokenizer for Java 9 and later #433
* [x] Various corrections and improvements to the api docs: #415, #417, #420, #428
* [x] Test for Gen.pick should be more succinct #450
* [x] Add support for `Either[T]` #409 
* [x] Fix `Gen.posNum` and `Gen.negNum` so it gives real numbers less than one #451 
* [x] Fix shrinking of commands in 2.12 #468
* [x] Fix stackoverflow of `Pretty.break` #476. 
* [x] Improve errors for test parameters #497.

There are a few PRs that are candidates but they need more review:

* [x] Show seed when failing test #400 
* [ ] Fixes for Dotty compiler #423
* [ ] Overridding `Properties.overrideParameters` doesn't override parameters #463
* [x] Deprecate ambiguous implicit in `Prop` for Dotty #498

**Comment by rickynils** [comment]
@ashawley What was your reason for closing this? I think a new ScalaCheck release in the near future sounds like a good idea, and it looks like you did thorough research before opening this issue?

**Comment by ashawley** [comment]
Feel free to open this back up.  

I closed it because I was going to write up a proposal for 1.15.0 release rather than 1.14.1, since there was a plan to add new `forAllShrink` methods and add deprecate warnings in #444.  However, Charles O'Farrell and I agreed it wasn't the best plan.

**Comment by nrinaudo** [comment]
I’d vote for merging #468, since the command api is barely usable (for me) without that fix

**Comment by ashawley** [comment]
And there's a good chance that #468, failure to shrink `Commands`, could be causing secondary problems, such as #476.

**Comment by rajit** [comment]
It looks like `1.14.1` might not be far off. Is there anything I can do to help with the release?

**Comment by ashawley** [comment]
I've added Dotty fixes in #423 to the list above, since it seems safe to include in 1.14.1.

**Comment by ashawley** [comment]
A lot has been merged, so I updated the list above.
